CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    CREATE TABLE "Artistas" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        "Biografia" text NOT NULL,
        "Tipo" text NOT NULL,
        CONSTRAINT "PK_Artistas" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    CREATE TABLE "Categorias" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        "Descripcion" text NOT NULL,
        "Icono" text NOT NULL,
        "PermitePrestamo" boolean NOT NULL,
        CONSTRAINT "PK_Categorias" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    CREATE TABLE "Usuarios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Email" text NOT NULL,
        "PasswordHash" text NOT NULL,
        "Rol" integer NOT NULL,
        CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    CREATE TABLE "Productos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Titulo" text NOT NULL,
        "Descripcion" text NOT NULL,
        "Precio" numeric(18,2) NOT NULL,
        "AnioLanzamiento" integer NOT NULL,
        "ImagenUrl" text NOT NULL,
        "CategoriaId" integer NOT NULL,
        CONSTRAINT "PK_Productos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Productos_Categorias_CategoriaId" FOREIGN KEY ("CategoriaId") REFERENCES "Categorias" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    CREATE TABLE "Clientes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Nombre" text NOT NULL,
        "Apellido" text NOT NULL,
        "Email" text NOT NULL,
        "Telefono" text NOT NULL,
        "FechaRegistro" timestamp with time zone NOT NULL,
        "Tipo" integer NOT NULL,
        "MaxPrestamosSiultaneos" integer NOT NULL,
        "UsuarioId" integer NOT NULL,
        CONSTRAINT "PK_Clientes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Clientes_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    CREATE TABLE "Inventarios" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ProductoId" integer NOT NULL,
        "StockTotal" integer NOT NULL,
        "StockDisponible" integer NOT NULL,
        "StockDisponiblePrestamo" integer NOT NULL,
        "StockEnPrestamo" integer NOT NULL,
        "StockMinimo" integer NOT NULL,
        CONSTRAINT "PK_Inventarios" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Inventarios_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    CREATE TABLE "ProductoArtistas" (
        "ProductoId" integer NOT NULL,
        "ArtistaId" integer NOT NULL,
        "Rol" text NOT NULL,
        CONSTRAINT "PK_ProductoArtistas" PRIMARY KEY ("ProductoId", "ArtistaId"),
        CONSTRAINT "FK_ProductoArtistas_Artistas_ArtistaId" FOREIGN KEY ("ArtistaId") REFERENCES "Artistas" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ProductoArtistas_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    CREATE TABLE "Prestamos" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FechaPrestamo" timestamp with time zone NOT NULL,
        "FechaDevolucionEsperada" timestamp with time zone NOT NULL,
        "FechaDevolucionReal" timestamp with time zone,
        "Estado" integer NOT NULL,
        "Multa" numeric(18,2),
        "ClienteId" integer NOT NULL,
        CONSTRAINT "PK_Prestamos" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Prestamos_Clientes_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Clientes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    CREATE TABLE "Ventas" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Fecha" timestamp with time zone NOT NULL,
        "Total" numeric(18,2) NOT NULL,
        "MetodoPago" text NOT NULL,
        "Estado" text NOT NULL,
        "ClienteId" integer NOT NULL,
        CONSTRAINT "PK_Ventas" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Ventas_Clientes_ClienteId" FOREIGN KEY ("ClienteId") REFERENCES "Clientes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    CREATE TABLE "PrestamoDetalles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Observaciones" text,
        "PrestamoId" integer NOT NULL,
        "ProductoId" integer NOT NULL,
        CONSTRAINT "PK_PrestamoDetalles" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PrestamoDetalles_Prestamos_PrestamoId" FOREIGN KEY ("PrestamoId") REFERENCES "Prestamos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PrestamoDetalles_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    CREATE TABLE "VentaDetalle" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Cantidad" integer NOT NULL,
        "PrecioUnitario" numeric(18,2) NOT NULL,
        "Subtotal" numeric(18,2) NOT NULL,
        "VentaId" integer NOT NULL,
        "ProductoId" integer NOT NULL,
        CONSTRAINT "PK_VentaDetalle" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VentaDetalle_Productos_ProductoId" FOREIGN KEY ("ProductoId") REFERENCES "Productos" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_VentaDetalle_Ventas_VentaId" FOREIGN KEY ("VentaId") REFERENCES "Ventas" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    CREATE UNIQUE INDEX "IX_Clientes_UsuarioId" ON "Clientes" ("UsuarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    CREATE UNIQUE INDEX "IX_Inventarios_ProductoId" ON "Inventarios" ("ProductoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    CREATE INDEX "IX_PrestamoDetalles_PrestamoId" ON "PrestamoDetalles" ("PrestamoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    CREATE INDEX "IX_PrestamoDetalles_ProductoId" ON "PrestamoDetalles" ("ProductoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    CREATE INDEX "IX_Prestamos_ClienteId" ON "Prestamos" ("ClienteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    CREATE INDEX "IX_ProductoArtistas_ArtistaId" ON "ProductoArtistas" ("ArtistaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    CREATE INDEX "IX_Productos_CategoriaId" ON "Productos" ("CategoriaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    CREATE INDEX "IX_VentaDetalle_ProductoId" ON "VentaDetalle" ("ProductoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    CREATE INDEX "IX_VentaDetalle_VentaId" ON "VentaDetalle" ("VentaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    CREATE INDEX "IX_Ventas_ClienteId" ON "Ventas" ("ClienteId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310143337_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260310143337_Initial', '9.0.3');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260310144333_InitialPostgres') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260310144333_InitialPostgres', '9.0.3');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260320203147_AgregaMetodosPagoYDirecciones') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260320203147_AgregaMetodosPagoYDirecciones', '9.0.3');
    END IF;
END $EF$;
COMMIT;